server:
  port: 8080
spring:
  security:
    user:
      name: admin
      password: admin123

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: "autenticacion"
  devtools:
    add-properties: false


management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui.path: /swagger-ui
  swagger-ui.operationsSorter: method
  swagger-ui.tagsSorter: alpha

logging:
  file:
    name: logs/iam-app.log    # crea (y sobreescribe al arrancar) logs/iam-app.log
  level:
    root: INFO
    com.crediya.iam: INFO
    io.r2dbc.mysql: WARN
    org.springframework.r2dbc: INFO

adapters:
  r2dbc:
    host: "localhost"
    port: 3306
    database: "crediya_loan"
    username: "root"
    password: "rootpassword"
